### ISSUE TITLE
WARNING: Deprecated in 2.3: elgg_view_input() is deprecated. Use elgg_view_field() 

### ISSUE THREAD

**Issue by Shopify-Duncan** [hypeJunction/hypeAttachments#1]
Updated to your newest push, still getting these errors.

WARNING: Deprecated in 2.3: elgg_view_input() is deprecated. Use elgg_view_field() Called from [#20] /home/content/18/9142018/html/HostedSites/Jon/social/vendor/elgg/elgg/engine/lib/views.php:1387<br /> -> [#19] /home/content/18/9142018/html/HostedSites/Jon/social/mod/hypeAttachments/views/default/plugins/hypeAttachments/settings.php:28

**Comment by hypeJunction** [comment]
Deprecation warnings are not errors.
